services:
  component_frontdoor:
    build:
      args:
        - gobuildopts=-cover
    environment:
      - GOCOVERDIR=/app/covdatafiles
    volumes:
      - $PWD/devstack/components/frontdoor/coverage:/app/covdatafiles:rw

  component_worker:
    build:
      args:
        - gobuildopts=-cover
    environment:
      - GOCOVERDIR=/app/covdatafiles
    volumes:
      - $PWD/devstack/components/worker/coverage:/app/covdatafiles:rw
