// Code generated by mockery v2.31.4. DO NOT EDIT.

package workflowclient

import mock "github.com/stretchr/testify/mock"

// MockWorkflowClientInterface is an autogenerated mock type for the WorkflowClientInterface type
type MockWorkflowClientInterface struct {
	mock.Mock
}

type MockWorkflowClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowClientInterface) EXPECT() *MockWorkflowClientInterface_Expecter {
	return &MockWorkflowClientInterface_Expecter{mock: &_m.Mock}
}

// NewMockWorkflowClientInterface creates a new instance of MockWorkflowClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflowClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflowClientInterface {
	mock := &MockWorkflowClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
