receivers:
  otlp:
    protocols:
      grpc:
        endpoint: dep_opentelemetry-collector:4317

exporters:
  jaeger:
    endpoint: dep_telemetry-jaeger:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [jaeger]
