name: build-and-verify

on:
  workflow_call:
    inputs:
      sonar-enabled:
        type: boolean
        description: sonarqube reporting enabled
        required: true

jobs:
  cache-setup:
    name: 'Cache setup'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          go-enabled: true
          java-enabled: false
          app-deps-enabled: false
          tool-deps-enabled: true

  verify:
    name: 'Verify static analysis'
    runs-on: ubuntu-latest
    needs:
      - cache-setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          go-enabled: true
          app-deps-enabled: true
          tool-deps-enabled: true

      - name: Run code verification
        shell: bash
        run: make verify

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: verify-reports
          retention-days: 7
          path: reports/

  verify-codegen:
    name: 'Codegen'
    runs-on: ubuntu-latest
    needs:
      - cache-setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          go-enabled: true
          java-enabled: true
          app-deps-enabled: true
          tool-deps-enabled: true

      - name: Run codegen
        shell: bash
        env:
          SKIP_PLANTUML_DIAGRAM_OUTPUT: true
        run: |
          make codegen;

      - name: Verify empty git diff
        shell: bash
        run: |
          make verify.empty-git-diff;

  unit-test:
    name: 'Unit test'
    runs-on: ubuntu-latest
    needs:
      - cache-setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          go-enabled: true
          app-deps-enabled: true
          tool-deps-enabled: true

      - name: Run unit tests
        shell: bash
        run: make test.unit.report

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-reports
          retention-days: 7
          path: reports/

  integration-test:
    name: 'Integration test'
    runs-on: ubuntu-latest
    needs:
      - cache-setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          go-enabled: true
          app-deps-enabled: true
          tool-deps-enabled: true

      - name: Enable podman remote socket
        shell: bash
        run: |
          systemctl --user enable --now podman.socket

      - name: Start the devstack
        shell: bash
        env:
          DEVSTACK_TARGET: components deps
        run: |
          make devstack.build-instrumented
          make devstack.start-instrumented

      - name: Run integration tests
        shell: bash
        run: |
          make test.integration.report

      - name: Capture coverage reports
        shell: bash
        env:
          TEST_SUITE: test.integration
        run: |
          make devstack.capture-coverage-reports

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-reports
          retention-days: 7
          path: reports/

      - name: Shutdown devstack
        if: always()
        shell: bash
        run: make devstack.stop

  report-sonarqube:
    name: 'Report sonarqube'
    if: inputs.sonar-enabled
    runs-on: ubuntu-latest
    needs:
      - verify
      - verify-codegen
      - unit-test
      - integration-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Setup
      #   uses: ./.github/actions/setup
      #   with:
      #     go-enabled: true
      #     app-deps-enabled: true
      #     tool-deps-enabled: true

      - uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: verify-reports
          path: reports/

      - uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: unit-test-reports
          path: reports/

      - uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: integration-test-reports
          path: reports/
